FROM node:20 AS build-stage 

WORKDIR /usr/src/app/todo-frontend

COPY ./todo-frontend .

ENV VITE_BACKEND_URL="http://localhost:8080/api"

RUN npm ci

RUN npm test

RUN npm run build


RUN npm install -g serve


CMD ["serve", "dist"]

FROM nginx:1.25-alpine

COPY --from=build-stage /usr/src/app/todo-frontend/dist /usr/share/nginx/html